# Generated by Django 4.1 on 2022-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(max_length=16)),
                ('city_name', models.CharField(max_length=100)),
                ('headline', models.TextField()),
                ('temperature_min_val', models.FloatField()),
                ('temperature_min_unit', models.CharField(max_length=8)),
                ('temperature_max_val', models.FloatField()),
                ('temperature_max_unit', models.CharField(max_length=8)),
                ('day_conditions', models.CharField(max_length=100)),
                ('day_precipitation', models.BooleanField(default=False)),
                ('night_conditions', models.CharField(max_length=100)),
                ('night_precipitation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
