# Generated by Django 4.1 on 2022-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweather',
            name='forecast_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
